# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)

Rails.application.load_tasks


# Added by DRW to get the server to run on a different port
task :server do
  `bundle exec rails s -p 3050`
end
